CREATE DATABASE crud_struct;
USE crud_struct;

CREATE TABLE persona (
  COD_TDOC varchar(3) NOT NULL,
  ID_PERSONA int(11) NOT NULL,
  NOMBRE varchar(45) NOT NULL,
  APELLIDO varchar(45) NOT NULL,
  DIRECCION varchar(45) NOT NULL,
  COD_ROL int(11) NOT NULL
);


INSERT INTO persona (COD_TDOC, ID_PERSONA, NOMBRE, APELLIDO, DIRECCION, COD_ROL) VALUES
("900", 80830, "LEO", "PINEDA", "CALLE 123", 101);


CREATE TABLE rol (
  COD_ROL int(11) NOT NULL,
  DESC_ROL varchar(45) NOT NULL
);


INSERT INTO rol (COD_ROL, DESC_ROL) VALUES
(100, "USUARIO"),
(101, "ADMINISTRADOR");


CREATE TABLE tipo_documento (
  COD_TDOC varchar(3) NOT NULL,
  DESC_TDOC varchar(45) NOT NULL
);


INSERT INTO tipo_documento (COD_TDOC, DESC_TDOC) VALUES
(900, "CEDULA DE CIUDADANIA"),
(901, "CEDULA DE EXTRANJERIA");


ALTER TABLE persona
  ADD PRIMARY KEY (COD_TDOC,ID_PERSONA);

ALTER TABLE rol
  ADD PRIMARY KEY (COD_ROL);


ALTER TABLE tipo_documento
  ADD PRIMARY KEY (COD_TDOC);

ALTER TABLE persona
  ADD CONSTRAINT fk_PERSONA_ROL1 FOREIGN KEY (COD_ROL)
  REFERENCES rol (COD_ROL) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT fk_PERSONA_TIPO_DOCUMENTO1 FOREIGN KEY (COD_TDOC)
  REFERENCES tipo_documento (COD_TDOC) ON DELETE NO ACTION ON UPDATE NO ACTION;


